title: Sung's Portfolio
logo: /assets/img/logo3.png
description: This portfolio presents my work in data analysis and UX design, highlighting projects that use machine learning tools, data visualization, and user-centered design to connect technology with real users and socially meaningful outcomes.

show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal

resume_button:
  text: "Linkedin"
  url: "https://www.linkedin.com/in/sun712k/"

navigation:
  - title: Data Analysis
    url: /
  - title: UX Design
    url: /ux-design/

# github:
#   zip_url: http://example.com/download.zip
#   resume_url: another value
#   repo_url: another value

